### ISSUE TITLE
How to build relic with various pairing curves?

### ISSUE THREAD

**Issue by vusirikala** [relic-toolkit/relic#110]
It seems like RELIC is supporting the following pairing curves now. I got this list from src/fp/relic_fp_param.c
BN_158, BN_254, BN_256, BN_382, BN_446, KSS_508, B12_381, B12_455, B24_477, BN_638, SS_1536
Does RELIC support any pairing curves other than these? 
I didn't understand how to select the curve though. In order to select B24_477 curve, should I just it build relic using
`cmake -DFP-PRIME=477`
For all these curves, what should I set `BN-PRECI` to? Are there any other parameters that I need to set? Can I chose the curve to use in my code directly?
What happens if I initialize `FP-PRIME` to a number not in the above list?

**Comment by dfaranha** [comment]
For the moment, you should stick to the presets available in the folder, which build the library for some of these curves. I'm currently working on a better interface for selecting parameters (given that the library is configured for a certain field size). Future work is to configure the library build for named curves instead of field sizes, but it's still work in progress.

**Comment by vusirikala** [comment]
I want to experiment on various curves that do not have presets. May I know how to set BN-PRECI in general?

**Comment by dfaranha** [comment]
There is no curve in RELIC defined over a 768-bit prime, which maybe explains the error.
