### ISSUE TITLE
Bench and Test doesnt build

### ISSUE THREAD

**Issue by maksim-ka** [relic-toolkit/relic#122]
Getting similar Error like #58  with riot and relic 0.4.1
with -DTEST=1
`[ 76%] Building C object test/CMakeFiles/test_ec.dir/test_ec.c.obj
[ 76%] Linking C executable ../bin/test_ec
gcc: error: gcc: No such file or directory
make[4]: *** [test/CMakeFiles/test_ec.dir/build.make:85: bin/test_ec] Error 1
make[4]: Leaving directory '/home/maksim/code/Relic_Hello-World/bin/pkg/native/relic'
make[3]: *** [CMakeFiles/Makefile2:206: test/CMakeFiles/test_ec.dir/all] Error 2
make[3]: Leaving directory '/home/maksim/code/Relic_Hello-World/bin/pkg/native/relic'
make[2]: *** [Makefile:141: all] Error 2
make[2]: Leaving directory '/home/maksim/code/Relic_Hello-World/bin/pkg/native/relic'
make[1]: *** [Makefile:16: all] Error 2
make[1]: Leaving directory '/home/maksim/code/RIOT/pkg/relic'
make: *** [/home/maksim/code/RIOT/Makefile.include:614: pkg-build-relic] Error 2
`
with -DBENCH=1
`[ 88%] Linking C executable ../bin/bench_rand
gcc: error: gcc: No such file or directory
make[4]: *** [bench/CMakeFiles/bench_rand.dir/build.make:85: bin/bench_rand] Error 1
make[3]: *** [CMakeFiles/Makefile2:201: bench/CMakeFiles/bench_rand.dir/all] Error 2
make[2]: *** [Makefile:130: all] Error 2
make[1]: *** [Makefile:16: all] Error 2
make: *** [/home/maksim/code/RIOT/Makefile.include:614: pkg-build-relic] Error 2
`

**Comment by dfaranha** [comment]
Can you test the latest version from the repository? From the output, looks like a linking problem.

**Comment by PeterKietzmann** [comment]
I've tried compiling [RIOT](https://github.com/PeterKietzmann/RIOT/tree/pkg_relic_benchs/tests/pkg_relic) + relic with current repository version (dd3570d3d8de826c1f7f697125cf10edc7954659) and `-DTEST=1 -DBENCH=1` but get similar results. Linking fails because there is no build (/bin stays empty). I assume that [cross-compiling](https://github.com/PeterKietzmann/RIOT/blob/pkg_relic_benchs/pkg/relic/Makefile#L30) prevents building tests/benchs properly, although /test/CMakeFiles/test_*.dir/ exist. Do you have other ideas @dfaranha? 

@tfar  might be interested in this as well.

**Comment by PeterKietzmann** [comment]
One other thing: When compiled with RIOT, objects get a ".obj" ending (test/CMakeFiles/test_rand.dir/test_rand.c.obj) whereas a plain build from relic results  in ".o" files (test/CMakeFiles/test_rand.dir/test_rand.c.o). Now I'm really no expert with build systems, but this doesn't indicate an inconsistency, does it?

**Comment by dfaranha** [comment]
I don't have the means to reproduce this issue. Can you give instructions?

**Comment by PeterKietzmann** [comment]
@dfaranha thanks for the immediate response and your initiative! In order to reproduce, you need to build RIOT which integrates relic as an external software package, so this might get a bit RIOT specific. Compiling for RIOT native (running in a Linux process) doesn't take many special tools under Linux. However, you can find instructions setting up you envoronment [here](https://github.com/RIOT-OS/Tutorials), if needed.
1. Check out my [RIOT branch](https://github.com/PeterKietzmann/RIOT/tree/pkg_relic_benchs) which includes the updated relic version.
2. Navigate to RIOT/tests/pkg_relic
3. Have a look at the main.c and Makefile in that folder. This is our current relic "demo application". In its current state, the branch has TESTS and BENCHS disabled. Build and run that program by `make all term`. A shell waits for you to type "s" in order to start. If everything went well you should see some output like
```
RIOT native interrupts/signals initialized.
LED_RED_OFF
LED_GREEN_ON
RIOT native board initialized.
RIOT native hardware initialization complete.

Help: Press s to start test, r to print it is ready
s
START
main(): This is RIOT! (Version: 2020.01-devel-1834-gc5adc-pkg_relic_benchs)
.
OK (1 tests)
```
4. Now enable tests/benchs by setting a value for `-DTESTS` and `-DBENCHS` in the applications [Makefile](https://github.com/PeterKietzmann/RIOT/blob/pkg_relic_benchs/tests/pkg_relic/Makefile#L42)
5. Re-build `make all` and you should get the above mentioned error.

Some useful information:
When building packages in RIOT, it downloads the remote repository to the applications /bin folder (RIOT/tests/pkg_relic/bin/pkg/native/relic/ in this particular case) and triggers the build of the external package from its own build system. Have a look at this [Makefile](https://github.com/PeterKietzmann/RIOT/blob/pkg_relic_benchs/pkg/relic/Makefile) which contains `cmake` and `make` calls for relic. I would have expected that this step could at least build relic tests, even when not linked.

**Comment by dfaranha** [comment]
I finally found the issue! RELIC was reusing the LINK environment variable that is defined by RIOT. I changed the behavior now to just refer to CMake for compile/build flags.
