### ISSUE TITLE
oh my god..why I don't know how to use this library?

### ISSUE THREAD

**Issue by wenweiye** [relic-toolkit/relic#231]
I think this library is very well written, but I don't know how to use it.
For example, I want ep_param_set(NIST_P256). But it compiles wrong. I found the method from the issue, build the corresponding sh file. But I didn't find NIST_P256! !
please tell me!
For example, I can't find a way to take the abscissa of an elliptic curve point and turn it into a large number!
This drives me crazy.
Please forgive my stupidity!

**Comment by dfaranha** [comment]
Hi,

The library is not very usable, since it's designed for researchers and I don't have time to spend writing extensive documentation for different use cases. If you paste some error message or code sample, I may be able to help. There are examples of how to achieve this in the ECDH implementation which uses the x coordinate as multiprecision integer: https://github.com/relic-toolkit/relic/blob/49bfcaf783cced772ef6e826a31a94ccb7bc3992/src/cp/relic_cp_ecdh.c#L86

**Comment by wenweiye** [comment]
> Hi,
> 
> The library is not very usable, since it's designed for researchers and I don't have time to spend writing extensive documentation for different use cases. If you paste some error message or code sample, I may be able to help. There are examples of how to achieve this in the ECDH implementation which uses the x coordinate as multiprecision integer:
> 
> https://github.com/relic-toolkit/relic/blob/49bfcaf783cced772ef6e826a31a94ccb7bc3992/src/cp/relic_cp_ecdh.c#L86

Hi, thank you very much for taking the time to answer my question. It took me some time to get a feel for this library. I see what you mean with a library designed for researchers. Because, I found that the library contains most of the current calculation methods and optimization methods. I think your design is designed to verify the correctness of the calculation. Thank you very much for your contribution to ECC computing. :)
